version: '2.1'
orbs: 
  terraform: circleci/terraform@3.0.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
    
      - terraform/install:
          arch: amd64
          os: linux
          terraform_version: 3.0.1
      - terraform/fmt:
          path: .
      - terraform/validate:
          path: .
      - terraform/init:
          backend: true
          
      - terraform/plan:
          backend_config_file: buggloussstate
          path: .
      - terraform/apply:
          backend_config_file: backend.hcl
          path: .
      - terraform/destroy:
          path: .
    working_directory: ~/src
workflows:
  single-job-lifecycle:
    jobs:
      - Bugglous-tries-circleci


     