 - run:
          name: terraform init plan fmt
          command: |
            cd terraform
            terraform init -input=false
            terraform fmt .
            terraform plan -input=false
  apply:
    working_directory: /terraform
    docker: 
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light 
    steps: